# Generated by Django 2.1.5 on 2019-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_landmark_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cluster1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='cluster2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='cluster3',
            field=models.IntegerField(default=0),
        ),
    ]
