# Generated by Django 2.1.5 on 2019-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190119_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='landmark',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
